### ISSUE TITLE
Unable to specify "GPU_MAX_ALLOC_PERCENT" or "GPU_USE_SYNC_OBJECTS".

### ISSUE THREAD

**Issue by SpencerCarstens** [gevans/pick#1]
When running latest stable of SGminer I get this error. An option to set these globally would be super useful.

```
[06:08:09] WARNING: GPU_MAX_ALLOC_PERCENT is not specified!
[06:08:09] WARNING: GPU_USE_SYNC_OBJECTS is not specified!
```

Thank you for making this. It's rad as hell!

**Comment by gevans** [comment]
I'm glad you're finding it useful so far! I agree that some defaults would be nice. I pushed a change to do that.

I just caught a bug with `pick-update`. You'll have to manually switch to the `develop` branch and do a `git pull` to test the change I just pushed. In the next release you'll be able to:

``` sh
$ pick update develop
```

**Comment by SpencerCarstens** [comment]
Thanks mate!
